### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by tungst993** [react-native-seoul/react-native-naver-login#70]
### Version of naver-login libraries
2.1.0

### Version of react-native
0.63.3

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Don't show error end return accessToken

### Actual behavior
Show error "Safari cannot open the page because the address is invalid" after click button cancel or Ok in "accessing private information" screen
![Screen Shot 2020-12-04 at 10 29 45](https://user-images.githubusercontent.com/33714414/101118452-a1b5df80-361b-11eb-91d4-4e303e02e1a6.png)

**Comment by sidongmen** [comment]
I also had your error, but I solved it in the following way.

**Comment by sidongmen** [comment]
I also had your error, but I solved it in the following way.

1. goto Xcode - info - URL Types - add Identifier "naverlogin", URL Schemes "The URL Schemes you set up"
2. goto ios folder - Pods - naveridlogin-sdk-ios folder - NaverThirdPartyLogin.framework - NaverThirdPartyConstantsForApp.h
   you can find four define constants. Change 'kServiceAppUrlScheme', 'kConsumerKey', 'kConsumerSecret', 'kServiceAppName'

**Comment by sidongmen** [comment]
"Safari cannot open the page because the address is invalid" 에러가 뜨시는 분들은 우선 Xcode를 열고 프로젝트 info 에서 URL Types 쪽에 identifier 이름을 "naverlogin"로 하고 URL Schemes 값은 네이버 개발자 홈피에서 설정한 내 애플리케이션 IOS의 url schemes를 입력해 추가해주시면 됩니다. 또한 ios 폴더 내에 Pods - naveridlogin-sdk-ios folder - NaverThirdPartyLogin.framework - NaverThirdPartyConstantsForApp.h 경로로 가시면 상수 4개가 보이실텐데 마찬가지로 개발자 홈피에서의 내 애플리케이션에 맞는 Client ID와 Client Secret키, UrlScheme, App이름으로 변경해주시면 됩니다.

**Comment by mym0404** [comment]
해당 [댓글](https://github.com/react-native-seoul/react-native-naver-login/issues/57#issuecomment-1283510165) 참고해주시면 될 것 같습니다.
